version: "3.9"

services:
  nodejs:
    container_name: nodejs
    build:
      dockerfile_inline: |
        FROM ${DOCKER_IMAGE}
        WORKDIR /projects
        CMD tail -f /dev/null
    environment:
      - DOCKER_IMAGE
    volumes:
      - .:/projects
