version: "3.9"

services:
  nextjs:
    container_name: ${APP_NAME}
    build:
      dockerfile_inline: |
        FROM ${DOCKER_IMAGE}
        WORKDIR /projects/${APP_NAME}
        COPY . .
        RUN apt update -y && apt upgrade -y
        EXPOSE 3000
        RUN npm i        
        CMD ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    environment:
      - APP_NAME
      - DOCKER_IMAGE
    volumes:
      - .:/projects/${APP_NAME}

networks:
  default:
    driver: bridge
    name: ${APP_NAME}
